DROP   PROCEDURE ALAN/GETBLOB;

CREATE PROCEDURE ALAN/GETBLOB
        ( IN  I_FILENAME CHAR (20),
          OUT O_PICT BLOB (5M) )
        LANGUAGE SQL READS SQL DATA
        P1: BEGIN
          DECLARE C1 CURSOR FOR
            SELECT BYTES FROM THNCILIB.AA_FILES
            WHERE FILENAME = I_FILENAME;
          DECLARE EXIT HANDLER FOR SQLEXCEPTION
            SET O_PICT = NULL;
          OPEN C1;
          FETCH C1 INTO O_PICT;
          CLOSE C1;
        END P1;
