DROP PROCEDURE ORDER_NEW;
DROP PROCEDURE ORDER_LOADHEADER;
DROP PROCEDURE ORDER_LOADITEMS;
DROP PROCEDURE ORDER_SAVEHEADER;
DROP PROCEDURE ORDER_SAVEITEM;
DROP PROCEDURE ORDER_CHKITEM;
DROP PROCEDURE ORDER_CHKPRICE;
DROP PROCEDURE ORDER_CHKQUANTITY;

CREATE PROCEDURE ORDER_NEW(
          IN CustNo DECIMAL(6,0)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_NEW_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_LOADHEADER(
          IN OrderNo CHAR(10)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_LOADHEADER_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_LOADITEMS(
          IN OrderNo CHAR(10)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_LOADITEMS_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_SAVEHEADER(
          IN OrderNo   CHAR(10),
          IN CustNo    DECIMAL(6,0),
          IN SCAC      CHAR(4),
          IN SHIPNAME  CHAR(30),
          IN SHIPADDR1 CHAR(30),
          IN SHIPADDR2 CHAR(30),
          IN SHIPADDR3 CHAR(30),
          IN BILLNAME  CHAR(30),
          IN BILLADDR1 CHAR(30),
          IN BILLADDR2 CHAR(30),
          IN BILLADDR3 CHAR(30),
          IN SHIPDATE  CHAR(10)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_SAVEHEADER_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_SAVEITEM(
          IN OrderNo   CHAR(10),
          IN LineNo    DECIMAL(3,0),
          IN ItemNo    CHAR(8),
          IN Qty       DECIMAL(5,0),
          IN Price     DECIMAL(9,2)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_SAVEITEM_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_CHKITEM(
          IN ItemNo    CHAR(8)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_CHKITEM_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_CHKPRICE(
          IN ItemNo    CHAR(8),
          IN Price     DECIMAL(9,2)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_CHKPRICE_SP)'
       PARAMETER STYLE GENERAL;

CREATE PROCEDURE ORDER_CHKQUANTITY(
          IN ItemNo    CHAR(8),
          IN Qty       DECIMAL(5,0)
       )
       LANGUAGE RPGLE
       NOT DETERMINISTIC
       CONTAINS SQL
       EXTERNAL NAME 'ALAN/ORDERR4(ORDER_CHKQUANTITY_SP)'
       PARAMETER STYLE GENERAL;
