Insert into CUSTF values( 0001,
                          'Scott Klement',
                          '321 Sesame St.',
                          'Hong Kong',
                          'HK',
                          ' ',
                          '2019-01-01',
                          'USERPRF');
Insert into CUSTF values( 0002,
                          'Alan Chan',
                          '1 Nathan Road',
                          'Hong Kong',
                          'HK',
                          ' ',
                          '2019-01-01',
                          'USERPRF');
Insert into CUSTF values( 0003,
                          'Lam Chan',
                          '13 Prince Road',
                          'Hong Kong',
                          'HK',
                          ' ',
                          '2019-01-01',
                          'USERPRF');
Insert into CUSTF values( 0004,
                          'Testing Customer 1',
                          'Testing Street 1',
                          'Hong Kong',
                          'HK',
                          ' ',
                          '2019-01-01',
                          'USERPRF');
Insert into CUSTF values( 0005,
                          'Testing Customer 2',
                          'Testing Street 2',
                          'Hong Kong',
                          'HK',
                          ' ',
                          '2019-01-01',
                          'USERPRF');

