Insert into CUSTFILE values( 12001,
                             'Scott Klement',
                             'System iNEWS Magazine',
                             '321 Sesame St.',
                             'Franklin, WI  53132',
                             'Wayne Madden',
                             'Penton Technology Media',
                             '123 29th St.',
                             'Loveland, CO.',
                             'UPSN',
                             4    )  WITH NC;
Insert into CUSTFILE values( 78412,
                             'John Q Public',
                             '123 Main St',
                             'Anytown, USA',
                             ' ',
                             'John Q Public',
                             '123 Main St',
                             'Anytown, USA',
                             ' ',
                             'RDWY',
                             1    )  WITH NC;
Insert into CUSTFILE values( 59898,
                             'International Widgets, Ltd.',
                             '42 Banahasky Ln',
                             'Finleyville, PA 15332-3526',
                             ' ',
                             'International Widgets, Ltd.',
                             'Billing and Payables',
                             '551 W 1750 N',
                             'ABRAHAM UT  84635-3067',
                             'AACT',
                             2    )  WITH NC;
Insert into CUSTFILE values( 31783,
                             'Computer Engineering, Inc.',
                             '9910 Elmwood Blvd',
                             'Fruitland, ID 83619',
                             ' ',
                             'Computer Engineering, Inc.',
                             '9910 Elmwood Blvd',
                             'Fruitland, ID 83619',
                             ' ',
                             'ABFC',
                             7    )  WITH NC;
Insert into ITEMFILE values( 'WD671YO',
                             'Yellow-Orange Widget',
                             15.99,
                             27.99,
                             10,
                             623 ) WITH NC;
Insert into ITEMFILE values( 'WD995RC',
                             'Red Widget w/ Cream',
                             1.25,
                             5.75,
                             1,
                             87 ) WITH NC;
Insert into ITEMFILE values( 'SH8000-H',
                             'Fish Salad Dressing',
                             4.25,
                             4.25,
                             3,
                             287 ) WITH NC;
